window.BLOG_ARTICLES = [
  {
    "id": "a-1789195584359",
    "title": "測試00222",
    "subtitle": "",
    "slug": "測試00222",
    "category": "營養品科普",
    "type": "文章",
    "excerpt": "賴清德我是不會區湖的",
    "tags": [],
    "cover": "assets/uploads/2026/09/測試00222-cover-moid32.jpg",
    "status": "Published",
    "featured": false,
    "publisherId": "person-1789182720866-hhno7",
    "publishedAt": "2026-09-12",
    "updatedAt": "2026-09-12",
    "content": "<p><u style=\"background-color: rgb(255, 241, 168);\"><span style=\"font-size: 17px;\"><span style=\"font-size: 18px;\"><span style=\"font-size: 19px;\">賴清德</span></span></span></u>我是不會區湖的</p>",
    "contentFormat": "html",
    "references": []
  },
  {
    "id": "a-1789137659559",
    "title": "",
    "subtitle": "",
    "slug": "article-1789137659559",
    "category": "營養品科普",
    "type": "文章",
    "excerpt": "從這裡開始寫。",
    "tags": [],
    "cover": "",
    "status": "Published",
    "featured": false,
    "publishedAt": "2026-09-11",
    "updatedAt": "2026-09-11",
    "content": "<p>從這裡開始寫。</p>",
    "contentFormat": "html",
    "references": []
  },
  {
    "id": "a-1789136987598",
    "title": "ㄗ",
    "subtitle": "",
    "slug": "ㄗ",
    "category": "減重醫學",
    "type": "文章",
    "excerpt": "從這裡開始寫。",
    "tags": [],
    "cover": "",
    "status": "Published",
    "featured": false,
    "publishedAt": "2026-09-10",
    "updatedAt": "2026-09-11",
    "content": "<p>從這裡開始寫。</p>",
    "contentFormat": "html",
    "references": []
  },
  {
    "id": "a-1789133325726",
    "title": "ㄕ說",
    "subtitle": "",
    "slug": "ㄕ說",
    "category": "營養品科普",
    "type": "文章",
    "excerpt": "從這裡開始寫。",
    "tags": [],
    "cover": "",
    "status": "Published",
    "featured": false,
    "publishedAt": "2026-09-11",
    "updatedAt": "2026-09-11",
    "content": "<p>從這裡開始寫。</p>",
    "contentFormat": "html",
    "references": []
  },
  {
    "id": "a-1789133132641",
    "title": "測試",
    "subtitle": "",
    "slug": "測試",
    "category": "營養品科普",
    "type": "文章",
    "excerpt": "從這裡開始寫。",
    "tags": [],
    "cover": "",
    "status": "Published",
    "featured": false,
    "publishedAt": "2026-09-11",
    "updatedAt": "2026-09-11",
    "content": "<p>從這裡開始寫。</p>",
    "contentFormat": "html",
    "references": []
  },
  {
    "id": "a-1789133070607",
    "title": "測試",
    "subtitle": "",
    "slug": "測試",
    "category": "營養品科普",
    "type": "文章",
    "excerpt": "從這裡開始寫。",
    "tags": [],
    "cover": "",
    "status": "Published",
    "featured": false,
    "publishedAt": "2026-09-11",
    "updatedAt": "2026-09-11",
    "content": "<p>從這裡開始寫。</p>",
    "contentFormat": "html",
    "references": []
  }
];
