window.BLOG_ARTICLES = [
  {
    "id": "a-1789136987598",
    "title": "ㄗ",
    "subtitle": "",
    "slug": "ㄗ",
    "category": "減重醫學",
    "type": "文章",
    "excerpt": "從這裡開始寫。",
    "tags": [],
    "cover": "",
    "status": "Published",
    "featured": false,
    "publishedAt": "2026-09-10",
    "updatedAt": "2026-09-11",
    "content": "<p>從這裡開始寫。</p>",
    "contentFormat": "html",
    "references": []
  },
  {
    "id": "a-1789133325726",
    "title": "ㄕ說",
    "subtitle": "",
    "slug": "ㄕ說",
    "category": "營養品科普",
    "type": "文章",
    "excerpt": "從這裡開始寫。",
    "tags": [],
    "cover": "",
    "status": "Published",
    "featured": false,
    "publishedAt": "2026-09-11",
    "updatedAt": "2026-09-11",
    "content": "<p>從這裡開始寫。</p>",
    "contentFormat": "html",
    "references": []
  },
  {
    "id": "a-1789133132641",
    "title": "測試",
    "subtitle": "",
    "slug": "測試",
    "category": "營養品科普",
    "type": "文章",
    "excerpt": "從這裡開始寫。",
    "tags": [],
    "cover": "",
    "status": "Published",
    "featured": false,
    "publishedAt": "2026-09-11",
    "updatedAt": "2026-09-11",
    "content": "<p>從這裡開始寫。</p>",
    "contentFormat": "html",
    "references": []
  },
  {
    "id": "a-1789133070607",
    "title": "測試",
    "subtitle": "",
    "slug": "測試",
    "category": "營養品科普",
    "type": "文章",
    "excerpt": "從這裡開始寫。",
    "tags": [],
    "cover": "",
    "status": "Published",
    "featured": false,
    "publishedAt": "2026-09-11",
    "updatedAt": "2026-09-11",
    "content": "<p>從這裡開始寫。</p>",
    "contentFormat": "html",
    "references": []
  }
];
