window.BLOG_ARTICLES = [
  {
    "id": "a-1789119169105",
    "title": "主角獎",
    "subtitle": "",
    "slug": "主角獎",
    "category": "藥學測試",
    "type": "文章",
    "excerpt": "從這裡開始寫。",
    "tags": [],
    "cover": "",
    "status": "Published",
    "featured": false,
    "publishedAt": "2026-09-11",
    "updatedAt": "2026-09-11",
    "content": "<p>從這裡開始寫。</p>",
    "contentFormat": "html",
    "references": []
  },
  {
    "id": "a-1789117032343",
    "title": "幹",
    "subtitle": "",
    "slug": "幹",
    "category": "藥學測試",
    "type": "文章",
    "excerpt": "科威特",
    "tags": [],
    "cover": "",
    "status": "Published",
    "featured": false,
    "publishedAt": "2026-09-11",
    "updatedAt": "2026-09-11",
    "content": "<h2><img src=\"assets/uploads/2026/09/幹-img1-1uttyey.jpg\" alt=\"文章圖片\"></h2><p>科威特</p>",
    "contentFormat": "html",
    "references": []
  },
  {
    "id": "a-1789106184653",
    "title": "2026 911 1:56測試",
    "subtitle": "",
    "slug": "2026-911-1-56測試",
    "category": "Medical Notes",
    "type": "文章",
    "excerpt": "從這裡開始寫。",
    "tags": [],
    "cover": "",
    "status": "Published",
    "featured": false,
    "publishedAt": "2026-09-11",
    "updatedAt": "2026-09-11",
    "content": "<p>從這裡開始寫。</p>",
    "contentFormat": "html",
    "references": []
  }
];
