/* SIGN WELL v24.14 · Arrow Cross + Reflect newsletter loader (Originkit-inspired rewrite) */
(()=>{'use strict';
const DPR=()=>Math.min(devicePixelRatio||1,innerWidth<700?1.35:1.75), TAU=Math.PI*2;
const VS=`attribute vec2 a;void main(){gl_Position=vec4(a,0.,1.);}`;
const RFS=`precision highp float;uniform vec2 r;uniform float t;float l(vec2 u,float o){float q=mod(u.x+u.y,.22);float s=0.;for(int i=0;i<5;i++){float d=fract(t-o+float(i)*.01)*5.-length(u)+q;s+=.0022*float(i*i)/max(abs(d),.0001);}return s;}void main(){vec2 u=(gl_FragCoord.xy*2.-r)/min(r.x,r.y);u*=2.7;vec3 c=vec3(l(u,0.),l(u,.018),l(u,.036));vec3 tint=mix(vec3(.96,.55,.72),vec3(.36,.68,1.),smoothstep(-.8,.8,u.x));c=min(c*.78*tint,1.);gl_FragColor=vec4(c,max(max(c.r,c.g),c.b)*.72);}`;
const AFS=`precision highp float;uniform vec2 r;uniform float t;float box(vec2 p,vec2 b){vec2 d=abs(p)-b;return length(max(d,0.))+min(max(d.x,d.y),0.);}void main(){vec2 p=(gl_FragCoord.xy*2.-r)/min(r.x,r.y);float a=t*.72;float ca=cos(a),sa=sin(a);p=mat2(ca,-sa,sa,ca)*p;float d=10.;for(int i=0;i<4;i++){float q=float(i)*1.5707963;vec2 c=vec2(cos(q),sin(q))*.58;vec2 v=p-c;float aa=-q+t*(i<2?1.:-1.);float cc=cos(aa),ss=sin(aa);v=mat2(cc,-ss,ss,cc)*v;float shaft=box(v-vec2(0.,.10),vec2(.055,.20));float head=max(abs(v.x)-(.18-(v.y+.12)*.45),abs(v.y+.18)-.12);d=min(d,min(shaft,head));}float al=smoothstep(.025,-.006,d);vec3 col=mix(vec3(.96,.58,.74),vec3(.43,.72,1.),clamp(p.x*.5+.5,0.,1.));float hi=smoothstep(.12,-.02,d);gl_FragColor=vec4(col*(.55+.45*hi),al);}`;
function prog(gl,fs){const sh=(ty,s)=>{const x=gl.createShader(ty);gl.shaderSource(x,s);gl.compileShader(x);return x},v=sh(gl.VERTEX_SHADER,VS),f=sh(gl.FRAGMENT_SHADER,fs),p=gl.createProgram();gl.attachShader(p,v);gl.attachShader(p,f);gl.linkProgram(p);gl.deleteShader(v);gl.deleteShader(f);return gl.getProgramParameter(p,gl.LINK_STATUS)?p:null}
function mount(canvas,fs,speed){const gl=canvas.getContext('webgl',{alpha:true,antialias:false,premultipliedAlpha:true});if(!gl)return()=>{};const p=prog(gl,fs);if(!p)return()=>{};gl.useProgram(p);const b=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,b);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array([-1,-1,3,-1,-1,3]),gl.STATIC_DRAW);const a=gl.getAttribLocation(p,'a');gl.enableVertexAttribArray(a);gl.vertexAttribPointer(a,2,gl.FLOAT,false,0,0);const ur=gl.getUniformLocation(p,'r'),ut=gl.getUniformLocation(p,'t');let raf=0,start=performance.now(),visible=true;const resize=()=>{const d=DPR(),w=Math.max(1,Math.round(canvas.clientWidth*d)),h=Math.max(1,Math.round(canvas.clientHeight*d));if(canvas.width!==w||canvas.height!==h){canvas.width=w;canvas.height=h}gl.viewport(0,0,w,h);gl.uniform2f(ur,w,h)};const ro=new ResizeObserver(resize);ro.observe(canvas);resize();const frame=n=>{if(!visible)return;gl.clearColor(0,0,0,0);gl.clear(gl.COLOR_BUFFER_BIT);gl.uniform1f(ut,(n-start)/1000*speed);gl.drawArrays(gl.TRIANGLES,0,3);raf=requestAnimationFrame(frame)};raf=requestAnimationFrame(frame);return(v=true)=>{visible=v;if(v&&!raf)raf=requestAnimationFrame(frame);if(!v&&raf){cancelAnimationFrame(raf);raf=0}}}
let current=null,stopBg=null,stopArrow=null;
function decorate(overlay){if(!overlay||overlay.dataset.swNlFx==='1')return;overlay.dataset.swNlFx='1';const card=overlay.querySelector('.newsletter-flow-card'),stage=overlay.querySelector('.nl-flow-loading');if(!card||!stage)return;const bg=document.createElement('canvas');bg.className='sw-nl-reflect';overlay.prepend(bg);const wrap=document.createElement('div');wrap.className='sw-nl-arrow-wrap';wrap.innerHTML='<canvas class="sw-nl-arrow"></canvas><div class="sw-nl-subcube" aria-hidden="true"><i class="face front"></i><i class="face back"></i><i class="face right"></i><i class="face left"></i><i class="face top"></i><i class="face bottom"></i></div>';stage.prepend(wrap);stopBg=mount(bg,RFS,.13);stopArrow=mount(wrap.querySelector('canvas'),AFS,1);}
function sync(){const o=document.getElementById('newsletterFlowOverlay');if(!o)return;decorate(o);const showing=o.classList.contains('show'),success=o.classList.contains('success');if(showing&&!success){document.documentElement.classList.add('sw-newsletter-lock');current=o;stopBg?.(true);stopArrow?.(true)}else{document.documentElement.classList.remove('sw-newsletter-lock');stopBg?.(false);stopArrow?.(false);if(!showing)current=null}}
new MutationObserver(sync).observe(document.documentElement,{subtree:true,childList:true,attributes:true,attributeFilter:['class']});sync();
addEventListener('keydown',e=>{if(current&&current.classList.contains('show')&&!current.classList.contains('success')&&(e.key==='Escape'||e.key==='PageDown'||e.key==='PageUp'||e.key===' '))e.preventDefault()},{capture:true});
})();